[general]
LOGIN = "asces-unita"
SENHA = "zY2eT7vNwfLTQczN"
URL_REGISTROS = "https://automacao.rubeus.com.br/clients/reports/bi-csv/download?client_name=ASCES-UNITA&token=6820d1b13b55f897de6a301786883be4&filename=registros&subfolder=/"
URL_CONTATOS = "https://automacao.rubeus.com.br/clients/reports/bi-csv/download?client_name=ASCES-UNITA&token=6820d1b13b55f897de6a301786883be4&filename=contatos&subfolder=/"
